/**
 * Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeatureReleaseDto } from './featureReleaseDto';
import { FeatureAssignmentDto } from './featureAssignmentDto';
import { FeaturePermissionOutput } from './featurePermissionOutput';


export interface FeatureDetailOutput { 
    id?: number;
    title?: string | null;
    description?: string | null;
    epicLink?: string | null;
    priorityId?: number;
    completedAt?: string | null;
    status?: string | null;
    release?: FeatureReleaseDto;
    createdBy?: string | null;
    createdAt?: string;
    assignments?: Array<FeatureAssignmentDto> | null;
    permissions?: FeaturePermissionOutput;
}

