/**
 * Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProjectResourceDto { 
    userId?: number;
    userName?: string | null;
    roleId?: number;
    roleName?: string | null;
    isLeader?: boolean;
}

