/**
 * Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectResourceDto } from './projectResourceDto';
import { ProjectTeamsOutput } from './projectTeamsOutput';


export interface ProjectOutput { 
    id?: number;
    name?: string | null;
    description?: string | null;
    budget?: number | null;
    duration?: number | null;
    durationUnit?: string | null;
    createdAt?: string;
    creatorName?: string | null;
    resourcesCount?: number;
    membershipStatusId?: number;
    resources?: Array<ProjectResourceDto> | null;
    groupedResources?: Array<ProjectTeamsOutput> | null;
}

