/**
 * Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface StageLookupDto { 
    id?: number;
    stageName?: string | null;
    sequence?: number;
    isDefault?: boolean;
}

